### ISSUE TITLE
Errors in the last ffmpeg step 

### ISSUE THREAD

**Issue by GCG82** [ajay-sainy/Wav2Lip-GFPGAN#2]
Hi,

Thanks for your project, your demo looks great. I have a couple errors in the ffmpeg last step.

Can you help me. Thanks!

Screen capture here: https://markuphero.com/share/IgN6xYsCMRIdhDHKXduR

**Comment by WeiLi1201** [comment]
revise 'concatFilePath' to  'concatTextFilePath' ,  that will be ok

**Comment by ajay-sainy** [comment]
Fixed!

Thanks @GCG82  for filing the issue and @WeiLi1201  for the solution!
