### ISSUE TITLE
TypeError: mel() takes 0 positional arguments but 2 positional arguments (and 3 keyword-only arguments) were given

### ISSUE THREAD

**Issue by tralala87** [ajay-sainy/Wav2Lip-GFPGAN#8]
I get TypeError: mel() takes 0 positional arguments but 2 positional arguments (and 3 keyword-only arguments) were given
despite having the right format and length.

**Comment by saravananbcs** [comment]
Try this. It worked for me.

`pip install librosa==0.9.1 `

**Comment by ajay-sainy** [comment]
Updated the dependencies. The issue should be fixed
